copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_OPenSsl.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Client\XClient_Socket.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Client\XClient_APIHelp.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AVHelp.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AVCollect.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_VideoCodec.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avcodec-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avdevice-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avfilter-8.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avformat-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avutil-57.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\postproc-56.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\swscale-6.dll" "./"