#pragma once
/********************************************************************
//    Created:     2022/04/24  16:26:53
//    File Name:   D:\XEngine_StreamMedia\XEngine_Source\XEngine_ModuleHelp\ModuleHelp_Define.h
//    File Path:   D:\XEngine_StreamMedia\XEngine_Source\XEngine_ModuleHelp
//    File Base:   ModuleHelp_Define
//    File Ext:    h
//    Project:     XEngine(网络通信引擎)
//    Author:      qyt
//    Purpose:     导出帮助模块定义
//    History:
*********************************************************************/
//////////////////////////////////////////////////////////////////////////
///                        导出的函数
//////////////////////////////////////////////////////////////////////////
extern "C" XLONG ModuleHelp_GetLastError(int *pInt_SysError = NULL);
/************************************************************************/
/*                         导出的JT1078帮助函数                         */
/************************************************************************/
/********************************************************************
函数名称：ModuleHelp_IDCard_CheckBirth
函数功能：检查身份证号生日
 参数.一：pSt_IDInfo
  In/Out：In
  类型：数据结构指针
  可空：N
  意思：输入要检查的身份结构
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_JT1078_BCDToString(XBYTE bySIMNumber[6], XCHAR* ptszMsgBuffer);
/********************************************************************
函数名称：ModuleHelp_JT1078_StringToBCD
函数功能：字符串转BCD
 参数.一：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要转换的缓冲区
 参数.二：pbySIMNumber
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出转换后的数据
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_JT1078_StringToBCD(LPCXSTR lpszMsgBuffer, XBYTE* pbySIMNumber);
/************************************************************************/
/*                         导出的SRT函数                                */
/************************************************************************/
/********************************************************************
函数名称：ModuleHelp_SrtCore_Start
函数功能：启动SRT
 参数.一：nPort
  In/Out：In
  类型：整数型
  可空：N
  意思：输入要绑定的端口
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_Start(int nPort);
/********************************************************************
函数名称：ModuleHelp_SrtCore_SetCallback
函数功能：设置数据回调函数
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_SetCallback(CALLBACK_NETCORE_SOCKET_NETEVENT_LOGIN fpCallePoll_Login, CALLBACK_NETCORE_SOCKET_NETEVENT_RECV fpCallePoll_Recv, CALLBACK_NETCORE_SOCKET_NETEVENT_LEAVE fpCallePoll_Leave, XPVOID lPLogin = NULL, XPVOID lPRecv = NULL, XPVOID lPLeave = NULL);
/********************************************************************
函数名称：ModuleHelp_SrtCore_Send
函数功能：发送指定数据给客户端
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：要操作的客户端
 参数.二：lpszMsgBuffer
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：发送的数据
 参数.三：nMsgLen
  In/Out：In
  类型：整数型
  可空：N
  意思：发送的大小
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_Send(LPCXSTR lpszClientAddr, LPCXSTR lpszMsgBuffer, int nMsgLen);
/********************************************************************
函数名称：ModuleHelp_SrtCore_GetStreamID
函数功能：获取流信息
 参数.一：hSocket
  In/Out：In
  类型：句柄
  可空：N
  意思：输入要操作的客户端
 参数.二：ptszSMSAddr
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出获取到的推流地址
 参数.三：pbPublish
  In/Out：Out
  类型：逻辑型指针
  可空：N
  意思：输出这个地址是推流还是拉流
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_GetStreamID(SRTSOCKET hSocket, XCHAR * ptszSMSAddr, bool* pbPublish);
/********************************************************************
函数名称：ModuleHelp_SrtCore_Close
函数功能：关闭一个指定的客户端
 参数.一：lpszClientAddr
  In/Out：In
  类型：常量字符指针
  可空：Y
  意思：输入关闭的客户端低脂
 参数.二：hSocket
  In/Out：In
  类型：句柄
  可空：Y
  意思：或者输入客户端句柄
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_Close(LPCXSTR lpszClientAddr = NULL, SRTSOCKET hSocket = 0);
/********************************************************************
函数名称：ModuleHelp_SrtCore_Destory
函数功能：销毁SRT服务
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_SrtCore_Destory();
/************************************************************************/
/*                         导出的RTSP函数                               */
/************************************************************************/
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetSMSAddr
函数功能：获得流媒体地址
 参数.一：lpszURLStr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的URL
 参数.二：ptszSMSAddr
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出获得的流媒体地址
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetSMSAddr(LPCXSTR lpszURLStr, XCHAR* ptszSMSAddr);
/********************************************************************
函数名称：ModuleHelp_Rtsp_CreateClient
函数功能：创建一个RTSP客户端管理器
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：nVControlID
  In/Out：In
  类型：整数型
  可空：N
  意思：视频ID
 参数.三：nAControlID
  In/Out：In
  类型：整数型
  可空：N
  意思：音频控制ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_CreateClient(LPCXSTR lpszClientID, int nVControlID, int nAControlID);
/********************************************************************
函数名称：ModuleHelp_Rtsp_DeleteClient
函数功能：删除一个RTSP客户端
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_DeleteClient(LPCXSTR lpszClientID);
/********************************************************************
函数名称：ModuleHelp_Rtsp_SetClient
函数功能：设置一个RTSP客户端管理器
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：nRTPPort
  In/Out：In
  类型：整数型
  可空：N
  意思：RTP端口
 参数.三：nRTCPPort
  In/Out：In
  类型：整数型
  可空：N
  意思：RTCP端口
 参数.四：nTrackID
  In/Out：In
  类型：整数型
  可空：N
  意思：所属端口音视频类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_SetClient(LPCXSTR lpszClientID, int nRTPPort, int nRTCPPort, int nTrackID);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetClient
函数功能：获取一个RTSP客户端管理器
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：pInt_RTPPort
  In/Out：In
  类型：整数型指针
  可空：N
  意思：RTP端口
 参数.三：pInt_RTCPPort
  In/Out：In
  类型：整数型指针
  可空：N
  意思：RTCP端口
 参数.四：nTrackID
  In/Out：In
  类型：整数型
  可空：N
  意思：所属端口音视频类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetClient(LPCXSTR lpszClientID, int* pInt_RTPPort, int* pInt_RTCPPort, bool bVideo = true);
/********************************************************************
函数名称：ModuleHelp_Rtsp_SetSession
函数功能：设置一个会话ID
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：lpszSessionStr
  In/Out：In
  类型：整数型指针
  可空：N
  意思：输入要设置的会话ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_SetSession(LPCXSTR lpszClientID, LPCXSTR lpszSessionStr);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetSession
函数功能：获取一个会话ID
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：ptszSessionStr
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出获取到的会话ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetSession(LPCXSTR lpszClientID, XCHAR* ptszSessionStr);
/********************************************************************
函数名称：ModuleHelp_Rtsp_SetSsrc
函数功能：设置一个RTSP的RTP关联的SSRC
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：lpszSsrcStr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要关联的SSRC
 参数.三：bVideo
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：输入关联的类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_SetSsrc(LPCXSTR lpszClientID, LPCXSTR lpszSsrcStr, bool bVideo = true);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetSsrc
函数功能：获取一个RTSP关联的SSRC
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：ptszSsrcStr
  In/Out：In
  类型：字符指针
  可空：N
  意思：输出关联的SSRC
 参数.三：bVideo
  In/Out：In
  类型：逻辑型
  可空：Y
  意思：输入关联的类型
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetSsrc(LPCXSTR lpszClientID, XCHAR* ptszSsrcStr, bool bVideo = true);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetTrack
函数功能：获取RTSP的TRACKID类型
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：nTrackID
  In/Out：In
  类型：整数型
  可空：N
  意思：输入TRACKID
 参数.三：pbVideo
  In/Out：Out
  类型：逻辑型指针
  可空：Y
  意思：输出是视频还是音频
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetTrack(LPCXSTR lpszClientID, int nTrackID, bool* pbVideo);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetRTPAddr
函数功能：获取RTP发送地址端口
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：ptszADDRStr
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出地址字符串
 参数.三：bVideo
  In/Out：In
  类型：逻辑型
  可空：N
  意思：输入是音频还是视频
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetRTPAddr(LPCXSTR lpszClientID, XCHAR* ptszADDRStr, bool bVideo);
/********************************************************************
函数名称：ModuleHelp_Rtsp_GetRTPAddr
函数功能：获取RTCP发送地址端口
 参数.一：lpszClientID
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：ptszADDRStr
  In/Out：Out
  类型：字符指针
  可空：N
  意思：输出地址字符串
 参数.三：bVideo
  In/Out：In
  类型：逻辑型
  可空：N
  意思：输入是音频还是视频
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtsp_GetRTCPAddr(LPCXSTR lpszClientID, XCHAR* ptszADDRStr, bool bVideo);
/************************************************************************/
/*                         导出的RTMP函数                               */
/************************************************************************/
/********************************************************************
函数名称：ModuleHelp_Rtmp_CreateSession
函数功能：创建一个rtmp会话
 参数.一：lpszURLAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入创建的地址
 参数.二：lpszURLStr
  In/Out：Out
  类型：常量字符指针
  可空：N
  意思：输入要解析的URL
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtmp_CreateSession(LPCXSTR lpszURLAddr, LPCXSTR lpszURLStr);
/********************************************************************
函数名称：ModuleHelp_Rtmp_GetSession
函数功能：获取会话名称
 参数.一：lpszURLAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
 参数.二：ptszLiveName
  In/Out：In
  类型：字符指针
  可空：N
  意思：输出RTMP的LIVE名称
 返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtmp_GetSession(LPCXSTR lpszURLAddr, XCHAR* ptszLiveName);
/********************************************************************
函数名称：ModuleHelp_Rtmp_DeleteSession
函数功能：删除一个RTMP客户端
 参数.一：lpszURLAddr
  In/Out：In
  类型：常量字符指针
  可空：N
  意思：输入要处理的客户端ID
返回值
  类型：逻辑型
  意思：是否成功
备注：
*********************************************************************/
extern "C" bool ModuleHelp_Rtmp_DeleteSession(LPCXSTR lpszURLAddr);