copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_BaseLib.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_Algorithm.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_Core.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_ManagePool.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_OPenSsl.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_NetXApi.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\NetHelp_APIHelp.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_SystemApi.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\HelpComponents_Packets.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\HelpComponents_XLog.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\RfcComponents_HttpProtocol.dll" "./"

copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_SDPProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_StreamClient.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_FLVProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_RTMPProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_RTSPProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\StreamMedia_HLSProtocol.dll" "./"
copy /y "D:\XEngine\XEngine_SourceCode\Debug\XEngine_AVHelp.dll" "./"