copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_OPenSsl.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_NetXApi.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_Client\XClient_Socket.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_Packets.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_DataBase.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\plugin\caching_sha2_password.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_XClient.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCoder\XEngine_AVHelp.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avcodec-58.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avdevice-58.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avfilter-7.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avformat-58.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\avutil-56.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\postproc-55.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\swresample-3.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\AVCodec\swscale-5.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\bson-1.0.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\mongoc-1.0.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\libmariadb.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\libpq.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\sqlite3.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\zlib1.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libcrypto-3-x64.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\libssl-3-x64.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_LibEx\nghttp2.dll" "./"