copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_BaseSafe.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Core\XEngine_Cryption.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_Client\XClient_Stream.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_Client\XClient_APIHelp.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_NetHelp\NetHelp_XSocket.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\NetHelp_APIHelp.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_NetHelp\NetHelp_APIAddr.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_Packets.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_RfcComponents\RfcComponents_HttpProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_RfcComponents\RfcComponents_NatProtocol.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_SDPProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_FLVProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_RTMPProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_RTSPProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_RTPProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_RTCPProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_StreamMedia\StreamMedia_HLSProtocol.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_AVHelp.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\XEngine_AudioCodec.dll" "./"

copy /y "%XEngine_Lib64%\XEngine_AVCodec\avcodec-60.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\avdevice-60.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\avfilter-9.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\avformat-60.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\avutil-58.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\postproc-57.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib64%\XEngine_AVCodec\swscale-7.dll" "./"