copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_BaseLib.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_BaseLib\XEngine_Algorithm.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_Core.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_ManagePool.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_Core\XEngine_OPenSsl.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_NetHelp\NetHelp_APIHelp.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_SystemSdk\XEngine_SystemApi.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_HelpComponents\HelpComponents_Packets.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_HelpComponents\HelpComponents_XLog.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_RfcComponents\RfcComponents_HttpProtocol.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_StreamMedia\StreamMedia_StreamClient.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_StreamMedia\StreamMedia_FLVProtocol.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_StreamMedia\StreamMedia_RTMPProtocol.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_AVCodec\XEngine_AVHelp.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avcodec-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avdevice-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avfilter-8.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avformat-59.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\avutil-57.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\postproc-56.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\swresample-4.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\AVCodec\swscale-6.dll" "./"

copy /y "%XEngine_Lib32%\XEngine_HelpComponents\zlib1.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\libcrypto-3.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_LibEx\libssl-3.dll" "./"
copy /y "%XEngine_Lib32%\XEngine_NetHelp\nghttp2.dll" "./"